#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PRIMARY='\033[0;32m';
DANGER='\033[0;31m';
NC='\033[0m';

# Log functions

log() {
  echo -e "${1}";
}

log_info() {
  echo -e "${PRIMARY}[info]${NC} ${1}";
}

log_error() {
  echo -e "${DANGER}[error]${NC} ${1}";
}

# Download functions

download_wget() {
  URL=$1; shift;
  OUTPUT=$1; shift;

  wget -O$OUTPUT $URL;
  if [[ "$?" -ne "0" ]];
  then
    log_error "Unable to download ${URL} to ${OUTPUT} ${?}";
    exit 1;
  fi
}

download_curl() {
  URL=$1; shift;
  OUTPUT=$1; shift;

  curl $URL -L --output $OUTPUT;
  if [[ "$?" -ne "0" ]];
  then
    log_error "Unable to download ${URL} to ${OUTPUT}";
    exit 1;
  fi
}

download() {
  mkdir -p "${SCRIPT_DIR}/.tools";

  which wget > /dev/null;
  if [[ "$?" -eq "0" ]];
  then
    download_wget $@;
  else
    which curl > /dev/null;
    if [[ "$?" -eq "0" ]];
    then
      download_curl $@;
    else
      log_error "Please install cURL or wget";
      exit 1;
    fi
  fi
}

# Ensure functions - Make sure that a program is present

JQ_PATH="jq";
ensure_jq() {
  which $JQ_PATH > /dev/null;
  if [[ "$?" -ne "0" ]];
  then
    export JQ_PATH="${SCRIPT_DIR}/.tools/jq";
    which $JQ_PATH > /dev/null;

    if [[ "$?" -ne "0" ]];
    then
      log_info "Downloading jq";

      if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        download 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64' $JQ_PATH;
        chmod +x $JQ_PATH;
      elif [[ "$OSTYPE" == "darwin"* ]]; then
        download 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64' $JQ_PATH;
        chmod +x $JQ_PATH;
      else
        log_error "Unsupported Operating System: ${OSTYPE}";
        exit 1;
      fi
    fi
  fi

  JQ_VERSION=$($JQ_PATH --version);
  log_info "Using jq ${JQ_VERSION} ($(which $JQ_PATH))";
}

DOTNET_PATH="dotnet";
ensure_dotnet() {
  ensure_jq;
  DOTNET_VERSION=$(cat "${SCRIPT_DIR}/global.json" | ${JQ_PATH} '.sdk.version' -r);

  which $DOTNET_PATH > /dev/null;
  EXIT_CODE=$?;
  if [[ "$EXIT_CODE" -eq "0" ]];
  then
    $DOTNET_PATH --list-sdks | grep $DOTNET_VERSION > /dev/null;
    EXIT_CODE=$?;
    if [[ "$EXIT_CODE" -ne "0" ]];
    then
      log_info "Unable to find dotnet sdk ${DOTNET_VERSION} using $(which dotnet)";
    fi
  fi

  if [[ "$EXIT_CODE" -ne "0" ]];
  then
    export DOTNET_PATH="${SCRIPT_DIR}/.tools/dotnet/dotnet";
    which $DOTNET_PATH > /dev/null;
    if [[ "$?" -ne "0" ]];
    then
      log_info "Downloading dotnet sdk ${DOTNET_VERSION}";

      DOTNET_INSTALLER_PATH="${SCRIPT_DIR}/.tools/dotnet-installer.sh";
      download 'https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh' $DOTNET_INSTALLER_PATH;
      chmod +x $DOTNET_INSTALLER_PATH;

      $DOTNET_INSTALLER_PATH --install-dir "${SCRIPT_DIR}/.tools/dotnet" --version $DOTNET_VERSION;
    fi
  fi

  log_info "Using dotnet ${DOTNET_VERSION} ($(which $DOTNET_PATH))";
}

# Action functions - these are exposed for calling

action_help() {
  echo 'TODO - Look at source, or .github/workflows/dotnet.yml for example';
}

action_restore() {
  ensure_dotnet;
  $DOTNET_PATH restore $@;
}

action_build() {
  ensure_dotnet;
  $DOTNET_PATH build $@
}

action_test() {
  ensure_dotnet;
  $DOTNET_PATH test $@
}

action_code_coverage() {
  ensure_dotnet;
  $DOTNET_PATH tool install dotnet-reportgenerator-globaltool --tool-path .tools
  "${SCRIPT_DIR}/.tools/reportgenerator" -reports:tests/Jsonificate.Tests/coverage.cobertura.xml -targetdir:artifacts/code-coverage -reporttypes:Cobertura
}

action_benchmark() {
  ensure_dotnet;
  $DOTNET_PATH benchmarks/Jsonificate.Benchmarks/bin/release/net5.0/Jsonificate.Benchmarks.dll;
}

action_pack() {
  ensure_dotnet;
  $DOTNET_PATH pack $@ src/Jsonificate/Jsonificate.csproj;
}

# Main function

ACTION="action_${1}";
shift;

type $ACTION &>/dev/null
if [[ "$?" -eq "0" ]];
then
  $ACTION $@
else
  action_help
fi
