name: .NET

on:
  push:
    branches: [ publish ]

  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: restore
      run: ./actions restore

    - name: build
      run: ./actions build --configuration Release --no-restore

    - name: test
      run: ./actions test --configuration Release --no-build --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura -- xunit.parallelizeAssembly=true xunit.parallelizeTestCollections=true

    - name: generate code coverage report
      run: ./actions code_coverage

    - name: upload code coverage report
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Cobertura
        path: artifacts/code-coverage

    - name: benchmark
      run: sudo ./actions benchmark

    - name: upload benchmark
      uses: actions/upload-artifact@v1.0.0
      with:
        name: BenchmarkDotNet
        path: BenchmarkDotNet.Artifacts/results

    - name: pack
      run: ./actions pack --configuration Release --no-restore --no-build
      if: ${{ contains(github.ref, 'refs/heads/publish') }}

    - name: upload package
      uses: actions/upload-artifact@v1.0.0
      if: ${{ contains(github.ref, 'refs/heads/publish') }}
      with:
        name: Jsonificate
        path: src/Jsonificate/bin/Release